# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFnZBUqZCdz8dJEpA1OPU_WMMQjJonIE
"""

# Import necessary libraries for web scraping and data manipulation
import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt

# Define a dictionary of college teams, categorized by gender and sport.
# Each key holds a list of URLs to their respective team rosters.
college_teams_ = {
                  'men_college_teams_swim':['https://csidolphins.com/sports/mens-swimming-and-diving/roster/2023-2024?view=2',
                                         'https://yorkathletics.com/sports/mens-swimming-and-diving/roster',
                                         'https://athletics.baruch.cuny.edu/sports/mens-swimming-and-diving/roster',
                                         'https://www.brooklyncollegeathletics.com/sports/mens-swimming-and-diving/roster/2022-23?view=2',
                                         'https://lindenwoodlions.com/sports/mens-swimming-and-diving/roster/2021-22?view=2',
                                         'https://mckbearcats.com/sports/mens-swimming-and-diving/roster',
                                         'https://ramapoathletics.com/sports/mens-swimming-and-diving/roster',
                                         'https://oneontaathletics.com/sports/mens-swimming-and-diving/roster/2024-25?view=2',
                                         'https://binghamtonbearcats.com/sports/mens-swimming-and-diving/roster/2021-22',
                                         'https://albrightathletics.com/sports/mens-swimming-and-diving/roster/2021-22'],

                    'women_college_teams_swim': ['https://csidolphins.com/sports/womens-swimming-and-diving/roster/2023-2024?view=2',
                                       'https://queensknights.com/sports/womens-swimming-and-diving/roster/2019-20',
                                       'https://yorkathletics.com/sports/womens-swimming-and-diving/roster',
                                       'https://athletics.baruch.cuny.edu/sports/womens-swimming-and-diving/roster/2021-22?view=2',
                                       'https://www.brooklyncollegeathletics.com/sports/womens-swimming-and-diving/roster/2022-23?view=2',
                                       'https://lindenwoodlions.com/sports/womens-swimming-and-diving/roster/2021-22?view=2',
                                       'https://mckbearcats.com/sports/womens-swimming-and-diving/roster?view=2',
                                       'https://ramapoathletics.com/sports/womens-swimming-and-diving/roster?view=2',
                                       'https://keanathletics.com/sports/womens-swimming-and-diving/roster?view=2',
                                       'https://oneontaathletics.com/sports/womens-swimming-and-diving/roster/2021-22?view=2'],


                    'men_college_teams_volleyball': ['https://ccnyathletics.com/sports/mens-volleyball/roster?view=2',
                                                    'https://lehmanathletics.com/sports/mens-volleyball/roster?view=2',
                                                     'https://johnjayathletics.com/sports/mens-volleyball/roster?view=2',
                                                     'https://athletics.baruch.cuny.edu/sports/mens-volleyball/roster?view=2',
                                                     'https://mecathletics.com/sports/mens-volleyball/roster/2024?view=2',
                                                     'https://www.huntercollegeathletics.com/sports/mens-volleyball/roster?view=2',
                                                     'https://yorkathletics.com/sports/mens-volleyball/roster'],

                    'women_college_teams_volleyball': ['https://bmccathletics.com/sports/womens-volleyball/roster/2022?view=2',
                                                       'https://yorkathletics.com/sports/womens-volleyball/roster',
                                                       'https://hostosathletics.com/sports/womens-volleyball/roster/2022-2023?view=2',
                                                       'https://bronxbroncos.com/sports/womens-volleyball/roster/2021?view=2',
                                                       'https://queensknights.com/sports/womens-volleyball/roster?view=2',
                                                       'https://augustajags.com/sports/wvball/roster?view=2',
                                                       'https://flaglerathletics.com/sports/womens-volleyball/roster?view=2',
                                                       'https://pacersports.com/sports/womens-volleyball/roster',
                                                       'https://www.lockhavenathletics.com/sports/womens-volleyball/roster?view=2']



                    }

# To comfirm the dictionary of college teams and their roster URLs was successful.
#college_teams_

# Define a function to scrape player names and heights from a list of URLs.
# It handles web requests, HTML parsing, data extraction, and basic cleaning.
def scrape_urls(url_list):
  processed_heights = []
  processed_names = []

  for url in url_list:
    headers = {
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36',
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
      'Accept-Language': 'en-US,en;q=0.9',
      'Connection': 'keep-alive'
      }

    page = requests.get(url, headers = headers)

    soup = BeautifulSoup(page.content, 'html.parser')
    if page.status_code == 200:
      # Extract player names
      raw_names = soup.find_all('td', class_='sidearm-table-player-name')
      for raw_name in raw_names:
        name = raw_name.get_text().strip()
        processed_names.append(name)

      # Extract player heights and convert to inches
      raw_heights = soup.find_all('td', class_='height')
      for raw_height in raw_heights:
        height_in_inches = None
        raw_height_text = raw_height.get_text().strip()
        if raw_height_text:
          try:
            x = raw_height_text.split('-')
            # Convert height from 'feet-inches' format to total inches
            if len(x) == 2 and x[0].isdigit() and x[1].isdigit():
              feet = float(x[0]) * 12
              inches = float(x[1])
              height_in_inches = feet + inches
            else:
              print(f"Warning: Malformed height format '{raw_height_text}'. Appending None for height.")
          except ValueError:
            print(f"Warning: Could not convert height '{raw_height_text}' to float. Appending None for height.")
        else:
          print(f"Warning: Empty height text found. Appending None for height.")

        processed_heights.append(height_in_inches)

    else:
      print(f'Failed to retrieve {url} with status code {page.status_code}')

  # Ensure lists are of equal length to avoid errors when creating DataFrame
  min_len = min(len(processed_names), len(processed_heights))
  processed_names = processed_names[:min_len]
  processed_heights = processed_heights[:min_len]

  # Create a pandas DataFrame from the scraped data
  college_teams_data = {
                  'Name': processed_names,
                  'Height': processed_heights
                }

  college_teams_df = pd.DataFrame(college_teams_data)

  return college_teams_df



# Scrape data for men's college swim teams using the defined URLs
men_college_teams_swim = scrape_urls( college_teams_['men_college_teams_swim']  )
# Save the scraped data to a CSV file
men_college_teams_swim.to_csv('Mens Swim Team Athletes.csv',index = False )

# Scrape data for women's college swim teams using the defined URLs
women_college_teams_swim = scrape_urls( college_teams_['women_college_teams_swim']  )
# Save the scraped data to a CSV file
women_college_teams_swim.to_csv('Womens Swim Team Athletes.csv', index = False)

# Scrape data for men's college volleyball teams using the defined URLs
men_college_teams_volleyball = scrape_urls( college_teams_['men_college_teams_volleyball']  )
# Save the scraped data to a CSV file
men_college_teams_volleyball.to_csv('Men volleyball Team Athletes.csv', index = False)

# Scrape data for women's college volleyball teams using the defined URLs
women_college_teams_volleyball = scrape_urls( college_teams_['women_college_teams_volleyball']  )
# Save the scraped data to a CSV file
women_college_teams_volleyball.to_csv('Women volleyball Team Athletes.csv', index = False)

# Calculate and print the average height for men's swim team
avg_men_swim_height = round(float(men_college_teams_swim['Height'].mean()),2)
print(f'Avg men swim height: {avg_men_swim_height} inches')

# Calculate and print the average height for women's swim team
avg_women_swim_height = round(float(women_college_teams_swim['Height'].mean()),2)
print(f'Avg women swim height: {avg_women_swim_height} inches')

# Calculate and print the average height for men's volleyball team
avg_men_volleyball_height = round(float(men_college_teams_volleyball['Height'].mean()),2)
print(f'Avg men volleyball height: {avg_men_volleyball_height} inches')

# Calculate and print the average height for women's volleyball team
avg_women_volleyball_height = round(float(women_college_teams_volleyball['Height'].mean()),2)
print(f'Avg women volleyball height: {avg_women_volleyball_height} inches')

# Define parameters for ranking
k = 5 # Number of top athletes to display
col = 'Height' # Column to rank by

# Calculate rank for men's college swim team based on height (descending)
men_college_teams_swim['rank'] = men_college_teams_swim[col].rank(method='dense', ascending=False)
# Filter for top 'k' athletes
result = men_college_teams_swim[men_college_teams_swim['rank'] <= k]
# Sort the results by rank and display
result.sort_values(by='rank')

# Define parameters for ranking
k = 5 # Number of top athletes to display
col = 'Height' # Column to rank by

# Calculate rank for women's college swim team based on height (descending)
women_college_teams_swim['rank'] = women_college_teams_swim[col].rank(method='dense', ascending=False)
# Filter for top 'k' athletes
result = women_college_teams_swim[women_college_teams_swim['rank'] <= k]
# Sort the results by rank and display
result.sort_values(by='rank')

# Define parameters for ranking
k = 5 # Number of top athletes to display
col = 'Height' # Column to rank by

# Calculate rank for men's college volleyball team based on height (descending)
men_college_teams_volleyball['rank'] = men_college_teams_volleyball[col].rank(method='dense', ascending=False)
# Filter for top 'k' athletes
result = men_college_teams_volleyball[men_college_teams_volleyball['rank'] <= k]
# Sort the results by rank and display
result.sort_values(by='rank')

# Define parameters for ranking
k = 5 # Number of top athletes to display
col = 'Height' # Column to rank by

# Calculate rank for women's college volleyball team based on height (descending)
women_college_teams_volleyball['rank'] = women_college_teams_volleyball[col].rank(method='dense', ascending=False)
# Filter for top 'k' athletes
result = women_college_teams_volleyball[women_college_teams_volleyball['rank'] <= k]
# Sort the results by rank and display
result.sort_values(by='rank')

men_college_teams_swim.describe()

women_college_teams_swim.describe()

men_college_teams_volleyball.describe()

women_college_teams_volleyball.describe()

# generate a pandas dataframe containing the avg height of the mens swim team and the mens volleyball team

sports_teams = ['Mens Swim Team', 'Mens Volleyball Team','Womens Swim Team','Women Volleyball Team', ]
avg_heights = [avg_men_swim_height, avg_men_volleyball_height,avg_women_swim_height, avg_women_volleyball_height]

# build a dictionary to organize the data
sports_data = {
                'Sports Teams' : sports_teams,
                'Avg Height': avg_heights
            }

sports_data_df = pd.DataFrame(sports_data)
sports_data_df



men_swim_tallest_data = men_college_teams_swim.sort_values(by='Height', ascending=False).head(5)[['Name', 'Height']].values.tolist()
men_swim_shortest_data = men_college_teams_swim.sort_values(by='Height', ascending=True).head(5)[['Name', 'Height']].values.tolist()

print("5 Tallest Men's Swim Team Players (Name, Height):\n", men_swim_tallest_data)
print("\n5 Shortest Men's Swim Team Players (Name, Height):\n", men_swim_shortest_data)

women_swim_tallest_data = women_college_teams_swim.sort_values(by='Height', ascending=False).head(5)[['Name', 'Height']].values.tolist()
women_swim_shortest_data = women_college_teams_swim.sort_values(by='Height', ascending=True).head(5)[['Name', 'Height']].values.tolist()

print("5 Tallest Women's Swim Team Players (Name, Height):\n", women_swim_tallest_data)
print("\n5 Shortest Women's Swim Team Players (Name, Height):\n", women_swim_shortest_data)

men_volleyball_tallest_data = men_college_teams_volleyball.sort_values(by='Height', ascending=False).head(5)[['Name', 'Height']].values.tolist()
men_volleyball_shortest_data = men_college_teams_volleyball.sort_values(by='Height', ascending=True).head(5)[['Name', 'Height']].values.tolist()

print("5 Tallest Men's Volleyball Team Players (Name, Height):\n", men_volleyball_tallest_data)
print("\n5 Shortest Men's Volleyball Team Players (Name, Height):\n", men_volleyball_shortest_data)

women_volleyball_tallest_data = women_college_teams_volleyball.sort_values(by='Height', ascending=False).head(5)[['Name', 'Height']].values.tolist()
women_volleyball_shortest_data = women_college_teams_volleyball.sort_values(by='Height', ascending=True).head(5)[['Name', 'Height']].values.tolist()

print("5 Tallest Women's Volleyball Team Players (Name, Height):\n", women_volleyball_tallest_data)
print("\n5 Shortest Women's Volleyball Team Players (Name, Height):\n", women_volleyball_shortest_data)

sports_data_df.plot.bar(x='Sports Teams' ,y ='Avg Height', rot=30, color='green')
plt.title('Avg Height of Swimming and Volleyball Team')
plt.show()

#plt.savefig('average_height_bar_graph.png')

plt.savefig("bar_chart.png")